version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels: [dependencies]
    groups:
      create-adsk-production:
        dependency-type: production
        patterns: ["*"]
      create-adsk-dev:
        dependency-type: development
        patterns: ["*"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels: [dependencies, github-actions]
